//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Local_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Islemler
    {
        public int Id { get; set; }
        public int Kullanici_Id { get; set; }
        public int Ogrenci_Id { get; set; }
        public System.DateTime İslem_Tarihi { get; set; }
        public string Yapilan_Islem { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Ogrenci Ogrenci { get; set; }
    }
}
